name: cd
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get commit sha
        id: commit_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Deploy to production
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          img_url: ${{ vars.DOCKERHUB_USERNAME }}%2fku-connect-api%3A${{ steps.commit_sha.outputs.sha_short }}
        run: |
          curl "$deploy_url&imgUrl=$img_url"
